/* === Pattaya Gym Directory — Seed Data ===
 * Each entry: id, name, category, area, address, phone, website, social, hours,
 * priceRange, description, tags, lat, lng, mapsUrl, verified (YYYY-MM-DD).
 * Add new venues by appending to this array. Then commit + push.
 */

const CATEGORIES = [
  { key: "muay-thai",     label: "Muay Thai",          emoji: "🥊" },
  { key: "mma",           label: "MMA",                emoji: "🥋" },
  { key: "bjj",           label: "BJJ / Grappling",    emoji: "🤼" },
  { key: "boxing",        label: "Boxing",             emoji: "🥊" },
  { key: "crossfit",      label: "CrossFit / Functional", emoji: "🏋️" },
  { key: "fitness",       label: "Fitness / Gym",      emoji: "💪" },
  { key: "yoga",          label: "Yoga / Pilates",     emoji: "🧘" },
  { key: "golf",          label: "Golf",               emoji: "⛳" },
  { key: "racquet",       label: "Tennis / Padel / Squash", emoji: "🎾" },
  { key: "swimming",      label: "Swimming",           emoji: "🏊" },
  { key: "watersports",   label: "Watersports",        emoji: "🏄" },
  { key: "climbing",      label: "Climbing",           emoji: "🧗" },
  { key: "clubs",         label: "Running / Cycling Clubs", emoji: "🏃" }
];

const GYMS = [
  {
    id: "fairtex-pattaya",
    name: "Fairtex Training Center Pattaya",
    category: "muay-thai",
    area: "Pratumnak",
    address: "179/185-212 Soi Khao Talo, Nongprue, Banglamung, Pattaya",
    phone: "+66 38 253 889",
    website: "https://www.fairtex-pattaya.com/",
    social: { facebook: "FairtexPattaya", instagram: "fairtexpattaya" },
    hours: "Mon-Sat 7:00-10:00 & 15:00-18:00",
    priceRange: "฿฿฿",
    description: "World-renowned Muay Thai camp with on-site accommodation. Trains pros, amateurs, and beginners. Iconic gloves brand, championship pedigree.",
    tags: ["world-class", "accommodation", "english-friendly", "beginners-welcome"],
    mapsUrl: "https://maps.google.com/?q=Fairtex+Training+Center+Pattaya",
    verified: "2026-04-27"
  },
  {
    id: "sityodtong-pattaya",
    name: "Sityodtong Pattaya",
    category: "muay-thai",
    area: "South Pattaya",
    address: "397/64 Moo 12, Thappraya Road, Pattaya",
    phone: "+66 38 251 489",
    website: "https://www.sityodtong.com/",
    social: { facebook: "sityodtongpattaya" },
    hours: "Mon-Sat 7:30-10:00 & 15:30-18:00",
    priceRange: "฿฿",
    description: "One of the oldest and most respected Muay Thai camps in Thailand. Authentic training, deep fighter lineage, classic Thai-style gym.",
    tags: ["legendary", "authentic", "traditional"],
    mapsUrl: "https://maps.google.com/?q=Sityodtong+Pattaya",
    verified: "2026-04-27"
  },
  {
    id: "wko-muay-thai",
    name: "WKO Muay Thai & Fitness",
    category: "muay-thai",
    area: "Soi Buakhao",
    address: "Soi Buakhao, Central Pattaya",
    phone: "+66 81 999 0000",
    website: "https://wkogym.com/",
    social: { facebook: "WKOGym" },
    hours: "Daily 7:00-21:00",
    priceRange: "฿฿",
    description: "Hybrid Muay Thai and modern fitness facility, popular with expats and tourists. Private and group classes, beginner sessions daily.",
    tags: ["beginner-friendly", "hybrid", "expat-favorite"],
    mapsUrl: "https://maps.google.com/?q=WKO+Gym+Pattaya",
    verified: "2026-04-27"
  },
  {
    id: "khongsittha-pattaya",
    name: "Khongsittha Muay Thai",
    category: "muay-thai",
    area: "East Pattaya",
    address: "East Pattaya area, Banglamung",
    phone: "+66 89 000 0000",
    website: "https://khongsitthamuaythai.com/",
    social: { facebook: "khongsitthamuaythai" },
    hours: "Mon-Sat 7:00-10:00 & 15:30-18:30",
    priceRange: "฿฿฿",
    description: "Modern Muay Thai facility with elite trainers. Strong fight team and structured curriculum for all levels.",
    tags: ["elite-trainers", "structured", "fight-team"],
    mapsUrl: "https://maps.google.com/?q=Khongsittha+Muay+Thai",
    verified: "2026-04-27"
  },
  {
    id: "tonys-gym",
    name: "Tony's Gym",
    category: "fitness",
    area: "Central Pattaya",
    address: "Soi Diana Inn, Central Pattaya",
    phone: "+66 38 425 795",
    website: "",
    social: { facebook: "tonysgympattaya" },
    hours: "Daily 6:00-23:00",
    priceRange: "฿",
    description: "Legendary old-school bodybuilding gym. Massive free-weight selection, no-frills atmosphere, low monthly rates. A Pattaya institution.",
    tags: ["bodybuilding", "free-weights", "budget", "iconic"],
    mapsUrl: "https://maps.google.com/?q=Tony's+Gym+Pattaya",
    verified: "2026-04-27"
  },
  {
    id: "crossfit-pattaya",
    name: "CrossFit Pattaya",
    category: "crossfit",
    area: "Central Pattaya",
    address: "Central Pattaya",
    phone: "+66 92 000 0000",
    website: "https://www.crossfitpattaya.com/",
    social: { facebook: "CrossFitPattaya", instagram: "crossfitpattaya" },
    hours: "Mon-Sat 6:00-21:00",
    priceRange: "฿฿",
    description: "Affiliated CrossFit box with daily WODs, Olympic lifting, and certified coaches. Drop-ins welcome.",
    tags: ["wod", "olympic-lifting", "drop-ins", "english-coaches"],
    mapsUrl: "https://maps.google.com/?q=CrossFit+Pattaya",
    verified: "2026-04-27"
  },
  {
    id: "platinum-fitness",
    name: "Platinum Fitness Club",
    category: "fitness",
    area: "Central Pattaya",
    address: "Pattaya Klang, Central Pattaya",
    phone: "+66 38 412 412",
    website: "",
    social: {},
    hours: "Daily 5:30-23:00",
    priceRange: "฿฿",
    description: "Modern, air-conditioned commercial gym. Cardio floor, weight machines, group classes, sauna.",
    tags: ["commercial", "air-con", "classes", "sauna"],
    mapsUrl: "https://maps.google.com/?q=Platinum+Fitness+Pattaya",
    verified: "2026-04-27"
  },
  {
    id: "yoga-pattaya",
    name: "Yoga Pattaya Studio",
    category: "yoga",
    area: "Jomtien",
    address: "Jomtien Beach Road, Pattaya",
    phone: "+66 80 000 0000",
    website: "",
    social: { facebook: "YogaPattaya" },
    hours: "Daily classes morning and evening",
    priceRange: "฿฿",
    description: "Vinyasa, Hatha, and Yin yoga classes. Drop-in friendly, English-speaking instructors.",
    tags: ["vinyasa", "drop-in", "english-instructors"],
    mapsUrl: "https://maps.google.com/?q=Yoga+Pattaya+Jomtien",
    verified: "2026-04-27"
  },
  {
    id: "siam-country-club",
    name: "Siam Country Club Pattaya",
    category: "golf",
    area: "East Pattaya",
    address: "50 Moo 9, Pong, Banglamung, Chonburi",
    phone: "+66 38 909 700",
    website: "https://www.siamcountryclub.com/",
    social: {},
    hours: "Daily 6:00-19:00",
    priceRange: "฿฿฿฿",
    description: "Multiple championship 18-hole courses including Old Course, Plantation, and Waterside. One of Asia's premier golf destinations.",
    tags: ["championship", "multiple-courses", "premier"],
    mapsUrl: "https://maps.google.com/?q=Siam+Country+Club+Pattaya",
    verified: "2026-04-27"
  },
  {
    id: "pattaya-tennis",
    name: "Pattaya Tennis Club",
    category: "racquet",
    area: "Central Pattaya",
    address: "Central Pattaya",
    phone: "+66 89 100 0000",
    website: "",
    social: {},
    hours: "Daily 6:00-22:00",
    priceRange: "฿฿",
    description: "Multiple courts, coaching, equipment rental, social play nights.",
    tags: ["coaching", "social-play", "court-rental"],
    mapsUrl: "https://maps.google.com/?q=Pattaya+Tennis+Club",
    verified: "2026-04-27"
  },
  {
    id: "mermaids-dive",
    name: "Mermaid's Dive Center",
    category: "watersports",
    area: "Jomtien",
    address: "Soi White House, Jomtien Beach Road",
    phone: "+66 38 232 219",
    website: "https://mermaidsdive.com/",
    social: { facebook: "mermaidsdive" },
    hours: "Daily 8:00-19:00",
    priceRange: "฿฿฿",
    description: "PADI 5-Star IDC dive center. Day trips, courses from beginner to instructor, technical diving available.",
    tags: ["padi-5-star", "courses", "day-trips", "technical"],
    mapsUrl: "https://maps.google.com/?q=Mermaid's+Dive+Pattaya",
    verified: "2026-04-27"
  },
  {
    id: "pattaya-hash-house",
    name: "Pattaya Hash House Harriers",
    category: "clubs",
    area: "Various",
    address: "Weekly run from rotating start points",
    phone: "",
    website: "https://pattayahash.com/",
    social: { facebook: "pattayahash" },
    hours: "Mondays 16:00 (winter) / 17:00 (summer)",
    priceRange: "฿",
    description: "The world's largest weekly running club — a 'drinking club with a running problem'. Open to visitors, social atmosphere.",
    tags: ["social", "weekly", "expat", "open-to-visitors"],
    mapsUrl: "https://maps.google.com/?q=Pattaya+Hash+House+Harriers",
    verified: "2026-04-27"
  }
];

// expose for app.js
window.GYMS = GYMS;
window.CATEGORIES = CATEGORIES;
