/* === Pattaya Gym Directory — Data === */
/*
 * Schema: id, name, category, area, address, phone, website, social {facebook,instagram},
 *   hours, priceRange (฿ to ฿฿฿฿), description, tags, mapsUrl, detailFile, verified
 *
 * detailFile points to venues/<id>.md for the long-form ultra-deep page.
 * Stubs (no detailFile) render with the data below; deep .md files override later.
 */

const CATEGORIES = [
  { key: "muay-thai",   label: "Muay Thai",                  emoji: "MT" },
  { key: "mma",         label: "MMA",                        emoji: "MMA" },
  { key: "bjj",         label: "BJJ / Grappling",            emoji: "BJJ" },
  { key: "boxing",      label: "Boxing",                     emoji: "BOX" },
  { key: "crossfit",    label: "CrossFit / Functional",      emoji: "CF" },
  { key: "fitness",     label: "Fitness / Gym",              emoji: "GYM" },
  { key: "yoga",        label: "Yoga / Pilates",             emoji: "YOGA" },
  { key: "golf",        label: "Golf",                       emoji: "GOLF" },
  { key: "racquet",     label: "Tennis / Padel / Squash",    emoji: "TEN" },
  { key: "swimming",    label: "Swimming",                   emoji: "SW" },
  { key: "watersports", label: "Watersports / Diving",       emoji: "WAVE" },
  { key: "climbing",    label: "Climbing",                   emoji: "CL" },
  { key: "clubs",       label: "Running / Cycling Clubs",    emoji: "RUN" },
  { key: "kids-youth",  label: "Kids / Youth Sports",        emoji: "KID" },
  { key: "equestrian",  label: "Equestrian",                 emoji: "HORSE" },
  { key: "adventure",   label: "Adventure / Multi-Sport",    emoji: "ADV" }
];

const GYMS = [
  // ============ MUAY THAI (deep pages + stubs) ============
  { id: "fairtex-pattaya", name: "Fairtex Training Center Pattaya", category: "muay-thai", area: "Naklua / North Pattaya", address: "99/9 Moo 5, North Pattaya Rd, Naklua, Bang Lamung 20150", phone: "+66 86 308 7031", website: "https://fairtextrainingcenter.com/", social: { facebook: "fairtex.muaythai.pattaya" }, hours: "Mon-Sat 07:30-10:30 & 15:30-18:30", priceRange: "฿฿฿", description: "World's largest Muay Thai resort camp. 9 rings, 17 trainers, on-site hotel & 25m pool. Champions: Yodsanklai, Stamp, Smilla Sundell, Saemapetch.", tags: ["world-class","accommodation","pool","english-friendly"], mapsUrl: "https://maps.google.com/?q=Fairtex+Training+Center+Pattaya", detailFile: "venues/fairtex-pattaya.md", verified: "2026-04-27" },
  { id: "sityodtong-pattaya", name: "Sityodtong Pattaya", category: "muay-thai", area: "Naklua / Nong Prue", address: "36/7 Moo 6, Nong Prue, Bang Lamung 20150", phone: "+66 38 251 489", website: "https://sityodtongthailand.com/", social: { facebook: "sityodtongmuaythai" }, hours: "Mon-Sat 08:00-10:00 & 15:00-17:30", priceRange: "฿฿", description: "Founded 1960 by Kru Yodtong. 57+ world champions including Samart Payakaroon. Trained Rob Kaman & Ramon Dekkers. Pilgrimage destination.", tags: ["legendary","authentic","lineage","fighter-track"], mapsUrl: "https://maps.google.com/?q=Sityodtong+Pattaya", detailFile: "venues/sityodtong-pattaya.md", verified: "2026-04-27" },
  { id: "wko-muay-thai", name: "WKO Muay Thai & Fitness (ISS Gym)", category: "muay-thai", area: "Central Pattaya / Pattaya Klang", address: "503/16 Moo 9, Pattaya Klang Rd, Nong Prue", phone: "+66 87 137 0841", website: "https://world-kumite.org/", social: { facebook: "ISS.Muay.Thai" }, hours: "Muay Thai 15:30-17:00 daily", priceRange: "฿", description: "Owner Sifu McInnes was first Westerner to ref Lumpinee (1993). Resident trainer Sakmongkol (231-20-4, 3x Lumpinee, 5x WMC). ~฿4,000/month.", tags: ["budget","legendary-trainer","central"], mapsUrl: "https://maps.google.com/?q=WKO+Pattaya+Klang", detailFile: "venues/wko-muay-thai.md", verified: "2026-04-27" },
  { id: "kombat-group-thailand", name: "Kombat Group Thailand", category: "muay-thai", area: "Huai Yai / East Pattaya", address: "49/1 Moo 4, Soi Chaknok 19, Huai Yai, Bang Lamung 20150", phone: "+66 81 099 9333", website: "https://www.kombatgroup.com/", social: { facebook: "kombatgroup" }, hours: "Year-round, two sessions/day Mon-Sat", priceRange: "฿฿฿", description: "All-inclusive multi-discipline camp. Christian Daghio's legacy (190 MT fights, 7x World Champ). Muay Thai+Boxing+MMA+BJJ+Krav. 6 rings. 5/5 TripAdvisor.", tags: ["all-inclusive","multi-discipline","accommodation","premium"], mapsUrl: "https://maps.google.com/?q=Kombat+Group+Thailand", detailFile: "venues/kombat-group-thailand.md", verified: "2026-04-27" },
  { id: "battle-conquer-gym", name: "Battle Conquer Gym Pattaya", category: "muay-thai", area: "Central Pattaya / near Pattaya Beach", address: "Central Pattaya, near Pattaya Beach", phone: "+66 98 085 3053", website: "https://battleconquerpattaya.com/", social: { facebook: "battleconquerpattaya" }, hours: "7 days/week, twice-daily group classes", priceRange: "฿฿", description: "Pattaya's only fully air-conditioned Muay Thai gym. Weight room, sauna, ice plunge. 7-day flexible scheduling, English-speaking trainers.", tags: ["air-conditioned","near-beach","weight-room","ice-plunge"], mapsUrl: "https://maps.google.com/?q=Battle+Conquer+Gym+Pattaya", detailFile: "venues/battle-conquer-gym.md", verified: "2026-04-27" },
  { id: "sor-klinmee", name: "Sor Klinmee Muay Thai Gym", category: "muay-thai", area: "Nong Prue / East Pattaya", address: "Nong Prue, Bang Lamung 20150", phone: "", website: "", social: { facebook: "sorklinmeegym" }, hours: "Mon-Sat, two-a-day", priceRange: "฿", description: "Family-run authentic Thai camp, founded 2009 by Mit Klinmee. Home of Sudsakorn Sor Klinmee (278W/330F). Drop-ins ~฿200-300.", tags: ["authentic","family-run","budget","fighter-camp"], mapsUrl: "https://maps.google.com/?q=Sor+Klinmee+Pattaya", detailFile: "venues/sor-klinmee.md", verified: "2026-04-27" },
  { id: "petchrungruang-gym", name: "Petchrungruang Gym", category: "muay-thai", area: "South Pattaya / Sukhumvit", address: "Soi Sukhumvit-Pattaya 50, Bang Lamung", phone: "+66 86 147 3166", website: "http://petchrungruang.com/", social: { facebook: "petchrungruanggym" }, hours: "3 sessions/day; Mon-Sat", priceRange: "฿", description: "Pattaya's 2nd-oldest gym (1986). Three generations of family. Head coach Khru Nu (Lumpinee 2nd-place, 90 fights). Home of Sylvie von Duuglas-Ittu (270+ fights).", tags: ["family-camp","authentic","sylvie","kids-program"], mapsUrl: "https://maps.google.com/?q=Petchrungruang+Gym+Pattaya", detailFile: "venues/petchrungruang-gym.md", verified: "2026-04-27" },
  { id: "rambaa-somdet-m16", name: "Rambaa Somdet M16 Muay Thai & MMA", category: "muay-thai", area: "Nong Prue / East Pattaya", address: "Nong Prue, Bang Lamung — adjacent to Sor Klinmee", phone: "", website: "", social: { instagram: "m16_pattaya" }, hours: "Mon-Sat, two-a-day", priceRange: "฿฿", description: "Personal camp of Rambaa M16 — Thailand's first MMA world champion (Shooto Flyweight 2009) + Muay Thai legend. Cage on site. 100m from Sor Klinmee.", tags: ["mma","muay-thai","world-champion-coach","cage"], mapsUrl: "https://maps.google.com/?q=Rambaa+M16+Pattaya", detailFile: "venues/rambaa-somdet-m16.md", verified: "2026-04-27" },
  { id: "venum-training-camp", name: "Venum Training Camp Pattaya", category: "muay-thai", area: "Off Thepprasit Rd / near Jomtien", address: "Soi Khopai 12, off Thepprasit Rd, Bang Lamung 20150", phone: "", website: "https://venom-mt.com/", social: { facebook: "venumtrainingcamp" }, hours: "Mon-Sat 07:00-09:00 & 15:00-18:00", priceRange: "฿฿", description: "Modern multi-discipline facility near Jomtien. Muay Thai, MMA, BJJ, Combat Fitness, S&C, kids program. 2 rings + cage/mat zone.", tags: ["multi-discipline","modern","near-beach","kids"], mapsUrl: "https://maps.google.com/?q=Venum+Training+Camp+Pattaya", detailFile: "venues/venum-training-camp.md", verified: "2026-04-27" },
  { id: "rage-fight-academy", name: "Rage Fight Academy", category: "muay-thai", area: "Jomtien / South Pattaya", address: "South Pattaya, 5 min from Dongtan and Jomtien beaches", phone: "", website: "https://ragefightacademy.com/", social: { facebook: "ragefightacademy" }, hours: "Mon-Sat, multi-discipline daily", priceRange: "฿฿", description: "Multi-discipline academy: Muay Thai, Boxing, BJJ, MMA, Cross Training. 3 rings + BJJ/MMA mats. Education Visa sponsor for long-stays.", tags: ["multi-discipline","bjj-strong","education-visa","near-beach"], mapsUrl: "https://maps.google.com/?q=Rage+Fight+Academy+Pattaya", detailFile: "venues/rage-fight-academy.md", verified: "2026-04-27" },
  { id: "silk-muay-thai", name: "Silk Muay Thai", category: "muay-thai", area: "Pattaya", address: "Pattaya, Bang Lamung", phone: "", website: "https://silkmuaythai.com/", social: { facebook: "Silkmuaythai" }, hours: "Mon-Sat 07:00-09:30 & 15:00-18:00", priceRange: "฿฿฿", description: "Premium boutique camp. 4.9/5 rated. All-inclusive packages from ฿25,500/month with private room + pool/sauna/spa + meals.", tags: ["boutique","premium","accommodation","spa"], mapsUrl: "https://maps.google.com/?q=Silk+Muay+Thai+Pattaya", detailFile: "venues/silk-muay-thai.md", verified: "2026-04-27" },
  { id: "pattaya-thai-boxing-fitness", name: "Pattaya Thai Boxing & Fitness Gym (Jomtien)", category: "muay-thai", area: "Jomtien Beach", address: "Soi 7, off Jomtien Beach Road, Pattaya", phone: "", website: "", social: {}, hours: "Afternoons (closes ~17:00)", priceRange: "฿", description: "Walk-in budget gym in Jomtien. ~฿300 for equipment + 4-5 rounds of pads. Pro fighter Champ on roster. Air fans, no AC.", tags: ["budget","walk-in","near-beach","casual"], mapsUrl: "https://maps.google.com/?q=Pattaya+Thai+Boxing+Fitness+Jomtien", detailFile: "venues/pattaya-thai-boxing-fitness.md", verified: "2026-04-27" },
  { id: "fight-evo360", name: "FIGHT EVO360", category: "muay-thai", area: "Pattaya (verify)", address: "Pattaya — verify exact at venue", phone: "", website: "", social: {}, hours: "Verify at venue", priceRange: "฿฿", description: "Combines traditional Muay Thai and boxing values with structured sports science and performance-based programming. Stub — needs deep research.", tags: ["sport-science","performance","modern"], mapsUrl: "https://maps.google.com/?q=FIGHT+EVO360+Pattaya", verified: "2026-04-27" },
  { id: "sitpholek-muay-thai", name: "Sitpholek Muay Thai Gym", category: "muay-thai", area: "Pattaya", address: "Pattaya — verify exact", phone: "", website: "", social: {}, hours: "Verify", priceRange: "฿฿", description: "Pattaya Muay Thai camp mentioned in 2025 best-of lists. Stub — needs deep research.", tags: ["authentic","stub"], mapsUrl: "https://maps.google.com/?q=Sitpholek+Muay+Thai+Pattaya", verified: "2026-04-27" },

  // ============ CROSSFIT / FUNCTIONAL ============
  { id: "crossfit-pattaya", name: "CrossFit Pattaya @ The Jungle Gym", category: "crossfit", area: "Nong Prue / Central-East Pattaya", address: "165/4 Moo 6, Nong Prue, Bang Lamung 20150", phone: "", website: "https://www.junglegympattaya.com/", social: { facebook: "JungleGymPattaya", instagram: "junglegympattaya" }, hours: "CrossFit Mon-Fri 09:00-10:00 & 19:00-20:00; Sat 09:00", priceRange: "฿฿", description: "Pattaya's only CrossFit affiliate. Multi-discipline: CrossFit + MMA + archery + dodgeball + slacklining. Coach Murray. UA & Decathlon partners.", tags: ["crossfit-affiliate","multi-discipline","archery","english-coaches"], mapsUrl: "https://maps.google.com/?q=Jungle+Gym+Pattaya", detailFile: "venues/crossfit-pattaya.md", verified: "2026-04-27" },

  // ============ FITNESS / COMMERCIAL GYMS ============
  { id: "tonys-gym", name: "Tony's Gym", category: "fitness", area: "Central Pattaya", address: "Soi Diana Inn, Central Pattaya", phone: "+66 38 425 795", website: "", social: { facebook: "tonysgympattaya" }, hours: "Daily 6:00-23:00", priceRange: "฿", description: "Legendary old-school bodybuilding gym. Massive free-weights, no-frills, low monthly. A Pattaya institution.", tags: ["bodybuilding","free-weights","budget","iconic"], mapsUrl: "https://maps.google.com/?q=Tony's+Gym+Pattaya", verified: "2026-04-27" },
  { id: "platinum-fitness", name: "Platinum Fitness Club", category: "fitness", area: "Central Pattaya", address: "Pattaya Klang, Central Pattaya", phone: "+66 38 412 412", website: "", social: {}, hours: "Daily 5:30-23:00", priceRange: "฿฿", description: "Modern AC commercial gym. Cardio, weight machines, group classes, sauna.", tags: ["commercial","air-con","classes","sauna"], mapsUrl: "https://maps.google.com/?q=Platinum+Fitness+Pattaya", verified: "2026-04-27" },
  { id: "coco-fitness", name: "Coco Fitness", category: "fitness", area: "Pattaya", address: "Pattaya — verify exact", phone: "", website: "", social: {}, hours: "Verify", priceRange: "฿฿", description: "Highly rated TripAdvisor commercial fitness gym. Stub — needs deep research.", tags: ["commercial","top-rated"], mapsUrl: "https://maps.google.com/?q=Coco+Fitness+Pattaya", verified: "2026-04-27" },
  { id: "universe-gym", name: "Universe Gym", category: "fitness", area: "Welcome Town / North Pattaya", address: "Welcome Town, off Sukhumvit Rd, North Pattaya", phone: "", website: "", social: {}, hours: "Verify at gym", priceRange: "฿฿", description: "Excellent machine assortment, multiple membership packages. North Pattaya commercial gym for varying ability levels.", tags: ["commercial","machines","north-pattaya"], mapsUrl: "https://maps.google.com/?q=Universe+Gym+Pattaya", verified: "2026-04-27" },
  { id: "fitz-club", name: "Fitz Club (Royal Cliff Hotels)", category: "fitness", area: "Pratumnak / Royal Cliff", address: "Royal Cliff Hotels Group, Pratumnak Hill", phone: "", website: "https://www.royalcliff.com/facilities/fitz-club/", social: {}, hours: "Daily extended hours", priceRange: "฿฿฿฿", description: "Award-winning luxury sports club: 7 tennis courts, 2 AC squash courts, table tennis, swimming, gym, professional coaching. Premium tier.", tags: ["luxury","tennis","squash","swimming","gym","kids-coaching"], mapsUrl: "https://maps.google.com/?q=Fitz+Club+Royal+Cliff+Pattaya", verified: "2026-04-27" },
  { id: "elite-gym-fitness", name: "Elite Gym & Fitness Pattaya", category: "fitness", area: "Pattaya", address: "Pattaya — verify exact", phone: "", website: "https://elitegympattaya.com/", social: { facebook: "elite.gym.pattaya" }, hours: "Daily extended", priceRange: "฿฿", description: "Modern facility with top-notch equipment. Integrates yoga and other fitness programs.", tags: ["commercial","modern","yoga"], mapsUrl: "https://maps.google.com/?q=Elite+Gym+Fitness+Pattaya", verified: "2026-04-27" },
  { id: "jetts-fitness-pattaya", name: "Jetts Fitness Pattaya", category: "fitness", area: "Multiple (Little Walk, Royal Garden)", address: "Little Walk Pattaya + Royal Garden locations", phone: "", website: "https://www.jetts.co.th/", social: {}, hours: "24/7", priceRange: "฿฿", description: "24/7 fitness chain with multiple locations across Thailand. No-contract memberships, modern equipment.", tags: ["chain","24-7","no-contract"], mapsUrl: "https://maps.google.com/?q=Jetts+Fitness+Pattaya", verified: "2026-04-27" },
  { id: "fitness-7", name: "Fitness 7", category: "fitness", area: "Avenue Pattaya / Central", address: "Avenue Pattaya, between 2nd Rd and Soi Buakhao", phone: "", website: "", social: {}, hours: "24 hours", priceRange: "฿฿", description: "2000+ sqm, 24-hour gym in Avenue Pattaya. Cardio, weights, free weights, boxing ring, functional training areas.", tags: ["24-7","large","boxing-ring","central"], mapsUrl: "https://maps.google.com/?q=Fitness+7+Avenue+Pattaya", verified: "2026-04-27" },
  { id: "true-fitness-pattaya", name: "True Fitness Pattaya", category: "fitness", area: "Pattaya", address: "Pattaya — verify exact", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "Popular fitness chain: HIIT, yoga, spinning. Modern facility, group classes, nutrition counseling.", tags: ["chain","classes","hiit","yoga"], mapsUrl: "https://maps.google.com/?q=True+Fitness+Pattaya", verified: "2026-04-27" },
  { id: "castra-gym", name: "Castra Gym", category: "fitness", area: "Soi Khao Talo / East Pattaya", address: "Soi Khao Talo, East Pattaya", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿", description: "Relaxed atmosphere from bodybuilders to general fitness. East Pattaya location, less touristy.", tags: ["bodybuilding","relaxed","east-pattaya"], mapsUrl: "https://maps.google.com/?q=Castra+Gym+Pattaya", verified: "2026-04-27" },
  { id: "sun-fitness-buakao", name: "SUN Fitness Buakao", category: "fitness", area: "Soi Buakhao / Naklua (3 branches)", address: "Soi Buakhao + Naklua + 3rd location", phone: "", website: "", social: { facebook: "100063609967196" }, hours: "Mon-Fri 07:00-00:00; Sat-Sun 09:00-00:00 (Naklua closes 22:00)", priceRange: "฿", description: "3-branch chain across Pattaya — single membership accesses all. Soi Buakhao + Naklua branches.", tags: ["chain","budget","late-hours","multi-location"], mapsUrl: "https://maps.google.com/?q=SUN+Fitness+Buakao+Pattaya", verified: "2026-04-27" },
  { id: "cross-pattaya-pratamnak", name: "Cross Pattaya Pratamnak", category: "fitness", area: "Pratumnak", address: "Cross Pattaya Pratamnak Hotel", phone: "", website: "https://www.crosspattayapratamnak.com/play", social: {}, hours: "Hotel hours", priceRange: "฿฿฿", description: "Hotel fitness facility with day-pass option. Pool, gym, activities.", tags: ["hotel-gym","day-pass","pratumnak"], mapsUrl: "https://maps.google.com/?q=Cross+Pattaya+Pratamnak", verified: "2026-04-27" },
  { id: "manhattan-pattaya-fitness", name: "Manhattan Pattaya Fitness", category: "fitness", area: "Pattaya", address: "Manhattan Pattaya Hotel", phone: "", website: "https://manhattanpattaya.com/facilities/swimming-pool/", social: {}, hours: "Hotel hours", priceRange: "฿฿", description: "Hotel-based fitness + swimming pool. Day pass available.", tags: ["hotel-gym","pool","day-pass"], mapsUrl: "https://maps.google.com/?q=Manhattan+Pattaya", verified: "2026-04-27" },

  // ============ YOGA / PILATES ============
  { id: "yoga-pattaya-studio", name: "Yoga Pattaya Studio", category: "yoga", area: "Thepprasit / Jomtien", address: "315/327 Thepprasit Soi 12, Pattaya", phone: "+66 95 573 9376", website: "https://yogapattaya.com/", social: { facebook: "yogapattaya" }, hours: "Daily morning + evening classes", priceRange: "฿฿", description: "Pattaya's first international yoga studio. Ashtanga, Mysore, Hatha, Vinyasa Flow, Stretching, Fitness Yoga. English/Russian/Thai.", tags: ["ashtanga","mysore","trilingual","established"], mapsUrl: "https://maps.google.com/?q=Yoga+Pattaya+Studio+Thepprasit", detailFile: "venues/yoga-pattaya-studio.md", verified: "2026-04-27" },
  { id: "yoga-haus-pattaya", name: "Yoga Haus Pattaya", category: "yoga", area: "Pattaya Klang / Central", address: "Pattaya Klang Road, Central Pattaya", phone: "", website: "", social: {}, hours: "Group + private most days", priceRange: "฿฿", description: "Pattaya's most prominent hot yoga studio. Modern fitness-yoga vibe with Hot Yoga and Fit Ball. Walkable central.", tags: ["hot-yoga","fit-ball","central","modern"], mapsUrl: "https://maps.google.com/?q=Yoga+Haus+Pattaya", detailFile: "venues/yoga-haus-pattaya.md", verified: "2026-04-27" },
  { id: "ashtanga-yoga-pattaya", name: "Ashtanga Yoga Pattaya", category: "yoga", area: "Pattaya", address: "Pattaya — verify exact", phone: "", website: "https://ashtangayogapattaya.weebly.com/", social: {}, hours: "Verify", priceRange: "฿฿", description: "Traditional Ashtanga yoga with hands-on adjustments. Mysore-style focus.", tags: ["ashtanga","mysore","traditional"], mapsUrl: "https://maps.google.com/?q=Ashtanga+Yoga+Pattaya", verified: "2026-04-27" },
  { id: "one-d-yoga-studio", name: "One-D Yoga Studio", category: "yoga", area: "Pattaya-Naklua Rd", address: "Pattaya-Naklua Road", phone: "", website: "", social: {}, hours: "Daily classes", priceRange: "฿฿", description: "Various classes: traditional Hatha, Vinyasa Flow, Yin Yoga. Modern studio.", tags: ["hatha","vinyasa","yin","naklua"], mapsUrl: "https://maps.google.com/?q=One-D+Yoga+Studio+Pattaya", verified: "2026-04-27" },
  { id: "nok-yoga-pattaya", name: "Nok Yoga Pattaya", category: "yoga", area: "Jomtien Beach", address: "Near Jomtien Beach", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿", description: "Range of yoga sessions for all levels in tranquil beach setting near Jomtien.", tags: ["beach-yoga","jomtien","beginner-friendly"], mapsUrl: "https://maps.google.com/?q=Nok+Yoga+Pattaya", verified: "2026-04-27" },
  { id: "balance-yoga-studio-pattaya", name: "Balance Yoga Studio Pattaya", category: "yoga", area: "Near sea", address: "Pattaya, near sea", phone: "", website: "https://balancepattaya.com/", social: {}, hours: "Daily", priceRange: "฿฿", description: "Yoga + sound healing. Steps from the sea. 'Island of harmony in sunny Pattaya'.", tags: ["yoga","sound-healing","wellness","near-sea"], mapsUrl: "https://maps.google.com/?q=Balance+Yoga+Studio+Pattaya", verified: "2026-04-27" },

  // ============ GOLF ============
  { id: "siam-country-club", name: "Siam Country Club Pattaya", category: "golf", area: "East Pattaya", address: "50 Moo 9, Pong, Banglamung, Chonburi", phone: "+66 38 909 700", website: "https://siamcountryclub.com/", social: {}, hours: "Daily 6:00-19:00", priceRange: "฿฿฿฿", description: "Multiple championship courses: Old Course (1970, Top 100 world), Plantation, Waterside. Asia's premier golf destination.", tags: ["championship","top-100-world","multiple-courses","premier"], mapsUrl: "https://maps.google.com/?q=Siam+Country+Club+Pattaya", verified: "2026-04-27" },
  { id: "laem-chabang-international", name: "Laem Chabang International Country Club", category: "golf", area: "Laem Chabang", address: "Laem Chabang, Chonburi", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿฿", description: "Jack Nicklaus design (1995). 27 holes. Widely considered the best golf course layout in Pattaya.", tags: ["nicklaus","championship","27-holes","best-in-pattaya"], mapsUrl: "https://maps.google.com/?q=Laem+Chabang+International+Country+Club", verified: "2026-04-27" },
  { id: "phoenix-gold-golf", name: "Phoenix Gold Golf & Country Club", category: "golf", area: "Pattaya region", address: "Pattaya region", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "Multiple loops with beginner-friendly options. Established Pattaya golf destination.", tags: ["beginner-friendly","multiple-loops"], mapsUrl: "https://maps.google.com/?q=Phoenix+Gold+Golf+Pattaya", verified: "2026-04-27" },
  { id: "burapha-golf-club", name: "Burapha Golf Club", category: "golf", area: "Sriracha (30 km from Pattaya)", address: "Sriracha district, Chonburi", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "36 holes designed for natural beauty (lakes, hills, palms). Hosted 2010 Thailand Open. Top tournament venue.", tags: ["36-holes","tournament-host","championship"], mapsUrl: "https://maps.google.com/?q=Burapha+Golf+Club", verified: "2026-04-27" },
  { id: "treasure-hill-golf", name: "Treasure Hill Golf Club", category: "golf", area: "60 km from Pattaya", address: "60 km from Pattaya", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿", description: "Par-72 course, established 1994. Popular for low green fees and enjoyable rounds.", tags: ["par-72","value","est-1994"], mapsUrl: "https://maps.google.com/?q=Treasure+Hill+Golf+Pattaya", verified: "2026-04-27" },
  { id: "chee-chan-golf", name: "Chee Chan Golf", category: "golf", area: "Pattaya region", address: "Pattaya region", phone: "", website: "https://cheechangolf.com/", social: {}, hours: "Daily", priceRange: "฿฿฿฿", description: "Featured premium destination golf course in Pattaya region.", tags: ["premium","destination"], mapsUrl: "https://maps.google.com/?q=Chee+Chan+Golf+Pattaya", verified: "2026-04-27" },
  { id: "chatrium-golf-soi-dao", name: "Chatrium Golf Resort Soi Dao", category: "golf", area: "Soi Dao", address: "Soi Dao, Chanthaburi area", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "27-hole course, driving range, pro shop, three-floor clubhouse with hotel, pool, locker rooms, spa, restaurants.", tags: ["27-holes","resort","driving-range","spa"], mapsUrl: "https://maps.google.com/?q=Chatrium+Golf+Resort+Soi+Dao", verified: "2026-04-27" },
  { id: "pattana-sports-resort", name: "Pattana Sports Resort", category: "golf", area: "Pattaya region", address: "Pattaya region", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "Mid-tier Pattaya regional golf and sports resort.", tags: ["resort","golf","sports"], mapsUrl: "https://maps.google.com/?q=Pattana+Sports+Resort+Pattaya", verified: "2026-04-27" },
  { id: "st-andrews-2000", name: "St. Andrews 2000 Pattaya", category: "golf", area: "Pattaya region", address: "Pattaya region", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "Pattaya golf course. Stub — needs deep research.", tags: ["championship"], mapsUrl: "https://maps.google.com/?q=St+Andrews+2000+Pattaya", verified: "2026-04-27" },
  { id: "khao-kheow-country-club", name: "Khao Kheow Country Club", category: "golf", area: "Pattaya region", address: "Pattaya region", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "Pattaya regional golf course. Stub — needs deep research.", tags: ["regional"], mapsUrl: "https://maps.google.com/?q=Khao+Kheow+Country+Club", verified: "2026-04-27" },
  { id: "bangpra-international", name: "Bangpra International Golf Club", category: "golf", area: "Bangpra", address: "Bangpra, Chonburi", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "Mid-tier Pattaya regional golf course.", tags: ["regional","mid-tier"], mapsUrl: "https://maps.google.com/?q=Bangpra+International+Golf", verified: "2026-04-27" },
  { id: "mountain-shadow-country-club", name: "Mountain Shadow Country Club", category: "golf", area: "Pattaya region", address: "Pattaya region", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "Pattaya regional golf course. Stub — needs deep research.", tags: ["regional"], mapsUrl: "https://maps.google.com/?q=Mountain+Shadow+Country+Club", verified: "2026-04-27" },
  { id: "pattaya-country-club", name: "Pattaya Country Club", category: "golf", area: "Pattaya", address: "Pattaya", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿", description: "Local Pattaya golf course. Stub — needs deep research.", tags: ["local"], mapsUrl: "https://maps.google.com/?q=Pattaya+Country+Club", verified: "2026-04-27" },
  { id: "pattaya-golf-driving-range", name: "Pattaya Golf Driving Range", category: "golf", area: "Pattaya", address: "Pattaya — verify exact", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿", description: "Standalone driving range with practice facilities.", tags: ["driving-range","practice"], mapsUrl: "https://maps.google.com/?q=Pattaya+Golf+Driving+Range", verified: "2026-04-27" },

  // ============ RACQUET SPORTS ============
  { id: "pattaya-tennis-club", name: "Pattaya Tennis Club", category: "racquet", area: "Central Pattaya", address: "Central Pattaya", phone: "+66 89 100 0000", website: "", social: {}, hours: "Daily 6:00-22:00", priceRange: "฿฿", description: "Multiple courts, coaching, equipment rental, social play nights.", tags: ["tennis","coaching","social-play"], mapsUrl: "https://maps.google.com/?q=Pattaya+Tennis+Club", verified: "2026-04-27" },
  { id: "greta-sport-club", name: "Greta Sport Club Pattaya / Greta Farms", category: "racquet", area: "Pattaya", address: "Pattaya — verify exact", phone: "", website: "https://liga.tennis/venue/greta-sport-club-pattaya", social: {}, hours: "Daily", priceRange: "฿฿", description: "6 covered tennis courts with rain protection. Beautifully constructed roofed tennis venue.", tags: ["tennis","covered-courts","6-courts"], mapsUrl: "https://maps.google.com/?q=Greta+Sport+Club+Pattaya", verified: "2026-04-27" },
  { id: "tara-tennis-club", name: "Tara Tennis Club", category: "racquet", area: "Pattaya", address: "Pattaya", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿", description: "Pattaya tennis club. Stub — needs deep research.", tags: ["tennis"], mapsUrl: "https://maps.google.com/?q=Tara+Tennis+Club+Pattaya", verified: "2026-04-27" },
  { id: "tos-tennis", name: "Tos Tennis Pattaya", category: "racquet", area: "Pattaya", address: "Pattaya", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿", description: "Pattaya tennis facility. Stub — needs deep research.", tags: ["tennis"], mapsUrl: "https://maps.google.com/?q=Tos+Tennis+Pattaya", verified: "2026-04-27" },
  { id: "siam-bayshore-tennis", name: "Siam Bayshore Resort (Tennis)", category: "racquet", area: "South Pattaya / Beach", address: "Siam Bayshore Resort, South Pattaya", phone: "", website: "", social: {}, hours: "Hotel hours", priceRange: "฿฿฿", description: "3 outdoor hard tennis courts. Hotel-based facility, day visitors welcome.", tags: ["tennis","hotel","outdoor","3-courts"], mapsUrl: "https://maps.google.com/?q=Siam+Bayshore+Resort+Pattaya", verified: "2026-04-27" },
  { id: "euro-badminton", name: "Euro Badminton", category: "racquet", area: "Soi Chaiyaphruek 2 / East Pattaya", address: "Soi Chaiyaphruek 2, East Pattaya", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿", description: "Badminton courts plus pool and eating area. East Pattaya.", tags: ["badminton","pool","food"], mapsUrl: "https://maps.google.com/?q=Euro+Badminton+Pattaya", verified: "2026-04-27" },
  { id: "diamond-badminton", name: "Diamond Badminton", category: "racquet", area: "Pattaya 3rd Road / South Pattaya", address: "Pattaya 3rd Road, South Pattaya", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿", description: "Several courts available off Pattaya 3rd Road, South Pattaya.", tags: ["badminton","south-pattaya"], mapsUrl: "https://maps.google.com/?q=Diamond+Badminton+Pattaya", verified: "2026-04-27" },
  { id: "pattaya-tennis-badminton-inter-club", name: "Pattaya Tennis & Badminton Inter Club", category: "racquet", area: "Pattaya", address: "Pattaya", phone: "", website: "https://liga.tennis/venue/pattaya-badminton-tennis-inter-club", social: {}, hours: "Daily", priceRange: "฿฿", description: "Multiple courts: pickleball, badminton, tennis, table tennis. Multi-racquet facility.", tags: ["tennis","badminton","pickleball","table-tennis"], mapsUrl: "https://maps.google.com/?q=Pattaya+Tennis+Badminton+Inter+Club", verified: "2026-04-27" },
  { id: "play-padel-pattaya", name: "Play Padel Pattaya", category: "racquet", area: "Pratumnak", address: "Kasetsin Soi 3, Pratumnak, Pattaya", phone: "", website: "https://www.playpadelpattaya.com/", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "Dedicated padel club in Pratumnak. Pattaya's first dedicated padel venue.", tags: ["padel","first-mover","pratumnak"], mapsUrl: "https://maps.google.com/?q=Play+Padel+Pattaya", verified: "2026-04-27" },
  { id: "pattaya-sports-club", name: "Pattaya Sports Club", category: "racquet", area: "Central Pattaya", address: "Pattaya", phone: "", website: "https://pattayasports.org/", social: {}, hours: "Daily", priceRange: "฿฿", description: "Multi-sport sports club with tennis and other facilities.", tags: ["multi-sport","tennis","social"], mapsUrl: "https://maps.google.com/?q=Pattaya+Sports+Club", verified: "2026-04-27" },

  // ============ SWIMMING ============
  { id: "manta-kids-pattaya", name: "Manta Kids Pattaya", category: "swimming", area: "Pattaya / IG Center", address: "IG Center Pattaya", phone: "", website: "https://www.igcenter-pattaya.com/en/manta-kids-pattaya-en/", social: {}, hours: "Verify", priceRange: "฿฿", description: "Premier kids swim academy. Head coach is former Thai national swimmer. ASCTA-certified instructors. ฿9,900/quarter (10 sessions).", tags: ["kids","swim-academy","certified-coaches","national-coach"], mapsUrl: "https://maps.google.com/?q=Manta+Kids+Pattaya", verified: "2026-04-27" },
  { id: "first-serve-sports-club", name: "First Serve Sports Club (Swimming)", category: "swimming", area: "Pattaya", address: "Pattaya — verify exact", phone: "", website: "https://www.firstservesportsclub.com/swimming-1", social: {}, hours: "Verify", priceRange: "฿฿", description: "Swim teaching by Swimming Association of Thailand-trained instructors. All ages, English or Thai.", tags: ["swim-coaching","all-ages","english"], mapsUrl: "https://maps.google.com/?q=First+Serve+Sports+Club+Pattaya", verified: "2026-04-27" },
  { id: "hard-rock-pool", name: "Hard Rock Hotel Pool (Day Pass)", category: "swimming", area: "Central Pattaya", address: "Hard Rock Hotel Pattaya", phone: "", website: "https://hotel.hardrock.com/pattaya/swimming-pool.aspx", social: {}, hours: "Hotel hours", priceRange: "฿฿฿", description: "World-famous free-form pool with artificial beach. Day pass option.", tags: ["day-pass","famous","artificial-beach"], mapsUrl: "https://maps.google.com/?q=Hard+Rock+Pattaya+Pool", verified: "2026-04-27" },
  { id: "pattaya-public-pool-naklua", name: "Naklua Public Swimming Pool", category: "swimming", area: "Naklua", address: "Naklua, Pattaya", phone: "", website: "", social: {}, hours: "Public hours", priceRange: "฿", description: "One of two public swimming pools in Pattaya. Naklua location.", tags: ["public","budget","naklua"], mapsUrl: "https://maps.google.com/?q=Naklua+Public+Pool+Pattaya", verified: "2026-04-27" },
  { id: "pattaya-public-pool-jomtien", name: "Jomtien Public Swimming Pool", category: "swimming", area: "Between South Pattaya and Jomtien", address: "Between South Pattaya and Jomtien", phone: "", website: "", social: {}, hours: "Public hours", priceRange: "฿", description: "One of two public swimming pools in Pattaya. South Pattaya / Jomtien border.", tags: ["public","budget","jomtien"], mapsUrl: "https://maps.google.com/?q=Jomtien+Public+Pool+Pattaya", verified: "2026-04-27" },

  // ============ WATERSPORTS / DIVING ============
  { id: "mermaids-dive", name: "Mermaid's Dive Center", category: "watersports", area: "Jomtien", address: "Soi White House, Jomtien Beach Road", phone: "+66 38 232 219", website: "https://mermaidsdive.com/", social: { facebook: "mermaidsdive" }, hours: "Daily 8:00-19:00", priceRange: "฿฿฿", description: "PADI 5-Star IDC dive center. Day trips, courses beginner to instructor, technical diving.", tags: ["padi-5-star","courses","day-trips"], mapsUrl: "https://maps.google.com/?q=Mermaid's+Dive+Pattaya", verified: "2026-04-27" },
  { id: "pattaya-dive-centre", name: "Pattaya Dive Centre", category: "watersports", area: "Beach Road", address: "Beach Road, Pattaya", phone: "", website: "https://www.divecentrepattaya.com/", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "Pattaya's only Beach Road PADI Dive Centre. 24+ years established. All PADI courses + Tec.", tags: ["padi","beach-road","tec","established"], mapsUrl: "https://maps.google.com/?q=Pattaya+Dive+Centre", verified: "2026-04-27" },
  { id: "seafari-padi-dive", name: "Seafari PADI Dive Centre", category: "watersports", area: "Pattaya Beach Road area", address: "Behind Mike's Mall, 2 min from Pattaya Beach Road", phone: "", website: "https://seafari.co.th/", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "British-owned PADI 5-Star IDC. 40+ years of diving experience in Thailand.", tags: ["padi-5-star","british-owned","established"], mapsUrl: "https://maps.google.com/?q=Seafari+Dive+Pattaya", verified: "2026-04-27" },
  { id: "pattaya-scuba-adventures", name: "Pattaya Scuba Adventures", category: "watersports", area: "Pattaya", address: "Pattaya", phone: "", website: "https://www.pattaya-scuba-adventures.com/", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "PADI dive center offering courses and guided diving trips around Pattaya.", tags: ["padi","courses","guided-trips"], mapsUrl: "https://maps.google.com/?q=Pattaya+Scuba+Adventures", verified: "2026-04-27" },
  { id: "no-limit-divers", name: "No Limit Divers Pattaya", category: "watersports", area: "Pattaya", address: "Pattaya", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "PADI 5-Star IDC with PADI Internship Programs. Pattaya-based dive center.", tags: ["padi-5-star","internship","instructor-track"], mapsUrl: "https://maps.google.com/?q=No+Limit+Divers+Pattaya", verified: "2026-04-27" },
  { id: "jomtien-dive-center", name: "Jomtien Dive Center", category: "watersports", area: "Jomtien", address: "Jomtien", phone: "", website: "https://jomtiendivecenter.com/", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "PADI 5-Star IDC. Highly rated by both customers and IDC candidates.", tags: ["padi-5-star","jomtien","idc-rated"], mapsUrl: "https://maps.google.com/?q=Jomtien+Dive+Center", verified: "2026-04-27" },
  { id: "clubloongchat-watersports", name: "Clubloongchat Watersports", category: "watersports", area: "Na Jomtien", address: "Na Jomtien Beach", phone: "", website: "https://www.clubloongchat.com/", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "Beachside watersports school: kitesurfing, wingfoiling, windsurfing, sailing, SUP. Expert lessons + rentals.", tags: ["kitesurf","wingfoil","windsurf","sup","sailing"], mapsUrl: "https://maps.google.com/?q=Clubloongchat+Na+Jomtien", verified: "2026-04-27" },
  { id: "kitesurf-pattaya", name: "Kitesurf Pattaya", category: "watersports", area: "South end Jomtien", address: "South end of Jomtien Beach", phone: "", website: "", social: {}, hours: "Daily wind-dependent", priceRange: "฿฿฿", description: "IKO-certified kitesurfing courses. Beginner package starts at $250 for 3 days.", tags: ["kitesurf","iko-certified","beginner-package"], mapsUrl: "https://maps.google.com/?q=Kitesurf+Pattaya", verified: "2026-04-27" },
  { id: "kba-kiteboarding-pattaya", name: "KBA - Kiteboarding Asia Pattaya", category: "watersports", area: "Pattaya", address: "Pattaya", phone: "", website: "https://kiteboardingasia.com/pattaya/", social: {}, hours: "Daily wind-dependent", priceRange: "฿฿฿", description: "Kiteboarding shop and school. International chain with Pattaya branch.", tags: ["kiteboarding","shop","school","chain"], mapsUrl: "https://maps.google.com/?q=KBA+Kiteboarding+Pattaya", verified: "2026-04-27" },
  { id: "wave-pattaya", name: "Wave Pattaya Watersports", category: "watersports", area: "Pattaya Beach", address: "Pattaya Beach", phone: "", website: "https://www.wavepattaya.com/", social: {}, hours: "Daily", priceRange: "฿฿", description: "Multi-sport watersports operator. Various Pattaya beach activities.", tags: ["multi-sport","beach"], mapsUrl: "https://maps.google.com/?q=Wave+Pattaya", verified: "2026-04-27" },

  // ============ CLIMBING ============
  { id: "deep-climbing-gym", name: "Deep Climbing Gym", category: "climbing", area: "Harbor Pattaya Mall (8th floor)", address: "Harbor Pattaya Shopping Mall, 8th floor", phone: "", website: "", social: { facebook: "deeppattaya" }, hours: "Mall hours", priceRange: "฿฿", description: "Pattaya's first indoor climbing gym. Air-conditioned, 10m wall, ocean theme. Top rope, auto-belay, lead, bouldering routes.", tags: ["first-in-pattaya","air-con","10m-wall","top-rope","lead","bouldering"], mapsUrl: "https://maps.google.com/?q=Deep+Climbing+Gym+Pattaya", verified: "2026-04-27" },
  { id: "bean-cow-climbing-gym", name: "Bean Cow Climbing Gym", category: "climbing", area: "Pattaya", address: "Pattaya — verify exact", phone: "", website: "https://www.beancowclimbing.com/", social: {}, hours: "Verify", priceRange: "฿฿", description: "Family-friendly climbing gym. 8m wall. Top rope + lead climbing. CWA-certified teachers, belayer services, top rope safety classes.", tags: ["family-friendly","cwa-certified","top-rope","lead","8m-wall"], mapsUrl: "https://maps.google.com/?q=Bean+Cow+Climbing+Gym+Pattaya", verified: "2026-04-27" },

  // ============ RUNNING / CYCLING CLUBS ============
  { id: "pattaya-hash-house", name: "Pattaya Hash House Harriers", category: "clubs", area: "Various (rotating)", address: "Weekly run from rotating start points", phone: "", website: "https://www.pattayah3.com/", social: { facebook: "308747049238960" }, hours: "Mondays 16:00 (winter) / 17:00 (summer)", priceRange: "฿", description: "First Pattaya hash, mixed running club since 1984. World's largest weekly running club. 'Drinking club with a running problem'.", tags: ["social","weekly","expat","est-1984"], mapsUrl: "https://maps.google.com/?q=Pattaya+Hash+House+Harriers", verified: "2026-04-27" },
  { id: "pattaya-monkey-hash-house", name: "Pattaya Monkey Hash House Harriers", category: "clubs", area: "Various (monthly)", address: "Various, monthly", phone: "", website: "https://pattayamonkeyh3.com/", social: {}, hours: "Every other odd-numbered month, 3rd Saturday", priceRange: "฿", description: "Pattaya hash variation. Runs every 2nd, odd-numbered month, usually 3rd Saturday. ~2.5h duration.", tags: ["monthly","social","longer-runs"], mapsUrl: "https://maps.google.com/?q=Pattaya+Monkey+Hash", verified: "2026-04-27" },

  // ============ KIDS / YOUTH SPORTS ============
  { id: "af-academy-football", name: "AF Academy", category: "kids-youth", area: "South + Central Pattaya", address: "South Pattaya (outdoor) + Central Pattaya (indoor)", phone: "", website: "https://www.afacademy.pro/en", social: {}, hours: "Year-round", priceRange: "฿฿", description: "Football school for children. Coaches with international children's coaching experience. Indoor + outdoor fields.", tags: ["football","kids","indoor","outdoor","international-coaches"], mapsUrl: "https://maps.google.com/?q=AF+Academy+Pattaya", verified: "2026-04-27" },
  { id: "pattaya-city-football-academy", name: "Pattaya City Football Academy", category: "kids-youth", area: "Pattaya", address: "Pattaya", phone: "", website: "", social: {}, hours: "After school", priceRange: "฿฿", description: "Bronze-level Academy License (Football Association of Thailand). Children ages 6-14.", tags: ["football","bronze-license","ages-6-14"], mapsUrl: "https://maps.google.com/?q=Pattaya+City+Football+Academy", verified: "2026-04-27" },
  { id: "planet-football-pattaya", name: "Planet Football Pattaya", category: "kids-youth", area: "Pattaya", address: "Pattaya", phone: "", website: "https://www.pattayafootball.com/", social: {}, hours: "Verify", priceRange: "฿฿", description: "Football academy for kids and youth in Pattaya.", tags: ["football","kids","youth"], mapsUrl: "https://maps.google.com/?q=Planet+Football+Pattaya", verified: "2026-04-27" },
  { id: "rusich-club-football", name: "Rusich Club (Russian Football)", category: "kids-youth", area: "Pattaya", address: "Pattaya", phone: "", website: "https://rusich.club/en/classes/football_en/", social: {}, hours: "After school", priceRange: "฿฿", description: "Russian-language football coaching for children ages 5-16.", tags: ["football","russian-language","ages-5-16"], mapsUrl: "https://maps.google.com/?q=Rusich+Club+Pattaya", verified: "2026-04-27" },
  { id: "regents-international-school-pattaya", name: "Regents International School Pattaya (Sports)", category: "kids-youth", area: "Pattaya", address: "Pattaya", phone: "", website: "https://www.nordangliaeducation.com/risp-pattaya/outstanding-experiences/sports-and-pe", social: {}, hours: "School hours", priceRange: "฿฿฿฿", description: "International school sports programs: basketball, football, swimming, athletics, rugby, cricket. For school students.", tags: ["multi-sport","school","basketball","rugby","cricket"], mapsUrl: "https://maps.google.com/?q=Regents+International+School+Pattaya", verified: "2026-04-27" },

  // ============ EQUESTRIAN ============
  { id: "horseshoe-point-resort", name: "Horseshoe Point Resort & Country Club", category: "equestrian", area: "Mabprachan Reservoir / East Pattaya", address: "Soi Siam Country Club, near Mabprachan Reservoir, Pattaya", phone: "", website: "", social: {}, hours: "Daily", priceRange: "฿฿฿", description: "1,500-acre equestrian + adventure mega-facility. International Riding School (est 1999). 5 indoor/outdoor arenas, 100+ horses (Lusitano, Appaloosa, Lipizzaner, Arabs, Warmbloods, Falabella, Thai pony). Polo. Paintball. Zipline. Mountain biking. Multi-sport field. Accommodation.", tags: ["equestrian","polo","paintball","zipline","mountain-biking","mega-facility","accommodation"], mapsUrl: "https://maps.google.com/?q=Horseshoe+Point+Pattaya", verified: "2026-04-27" },

  // ============ NEW DISCOVERIES (added 2026-04-27) ============
  { id: "muscle-factory-pattaya", name: "Muscle Factory Pattaya", category: "fitness", area: "Pratamnak Hill", address: "Pratamnak Hill, Pattaya", phone: "", website: "https://mfbkk.com/", social: { facebook: "musclefactorypattaya" }, hours: "Daily extended", priceRange: "฿฿", description: "Largest hardcore gym in Pattaya. Multi-floor 3-story Pratamnak bodybuilding institution. Bangkok sister gym. Industrial fans, no AC.", tags: ["hardcore","largest","bodybuilding","powerlifting","pratamnak"], mapsUrl: "https://maps.google.com/?q=Muscle+Factory+Pattaya", verified: "2026-04-27" },
  { id: "cartoon-network-amazone", name: "Cartoon Network Amazone / Columbia Pictures Aquaverse", category: "swimming", area: "Na Jomtien / Sattahip", address: "888 Moo 8, Na Jomtien, Sattahip 20250", phone: "", website: "https://www.aquaverse.co.th/", social: {}, hours: "Daily 10:00-18:00", priceRange: "฿฿฿", description: "World first themed waterpark. 18 slides across 3 zones. Polin Waterparks hardware. Rebranded 2022 to Sony Pictures IPs. 15km south of Pattaya.", tags: ["waterpark","slides","family","day-trip","themed"], mapsUrl: "https://maps.google.com/?q=Cartoon+Network+Amazone+Pattaya", verified: "2026-04-27" },
  { id: "easykart-pattaya", name: "EasyKart Pattaya Thepprasit", category: "adventure", area: "Thepprasit Road", address: "Thepprasit Road, Pattaya", phone: "", website: "https://easykart.net/pattaya-easykart-book-now/", social: {}, hours: "Daily 10:00-01:00", priceRange: "฿฿", description: "Newest go-kart facility in Pattaya. Outdoor 350m beginner + 800m racing tracks. Multi-tier classes: Kids/Regular/Fast/2-Seater. From 480 baht.", tags: ["karting","adventure","family","outdoor","thepprasit"], mapsUrl: "https://maps.google.com/?q=EasyKart+Pattaya", verified: "2026-04-27" },
  { id: "fast-pro-football-academy", name: "FAST PRO Football Academy Pattaya", category: "kids-youth", area: "Horseshoe Point + IP Soccer Club", address: "Horseshoe Point Pattaya + IP Soccer Club Pattaya", phone: "", website: "https://www.fastprofootball.com/", social: { facebook: "fastprofootball" }, hours: "After-school sessions", priceRange: "฿฿฿", description: "UEFA-A licensed European football coach. Ages 4-15. Two locations. European-style technical + tactical + character training.", tags: ["football","uefa-a","european-coach","kids","premium"], mapsUrl: "https://maps.google.com/?q=FAST+PRO+Football+Academy+Pattaya", verified: "2026-04-27" },
  { id: "golf-hub-pattaya", name: "Golf Hub Pattaya (Indoor Simulator + Club Fitting)", category: "golf", area: "Soi Buakhao + East Pattaya", address: "Soi Buakhao + East Pattaya locations", phone: "", website: "https://www.golfhubpattaya.com/", social: {}, hours: "Daily", priceRange: "฿฿", description: "Only premium indoor simulator + club fitting in Pattaya. TrackMan / GC Quad launch monitor. AC year-round practice. Multiple locations.", tags: ["indoor","simulator","trackman","club-fitting","AC"], mapsUrl: "https://maps.google.com/?q=Golf+Hub+Pattaya", verified: "2026-04-27" },

  { id: "ramayana-water-park", name: "Ramayana Water Park", category: "swimming", area: "Na Jomtien / Sattahip", address: "9 9, Tambon Na Chom Thian, Sattahip 20250", phone: "", website: "https://www.ramayanawaterpark.com/", social: {}, hours: "Daily 10:00-18:00", priceRange: "฿฿฿", description: "Largest water park in Thailand and Southeast Asia. 184,000 sqm. 26 slides / 34 lanes. 600m lazy river around natural hill. Double wave pool with 150m beach. TripAdvisor 2019 #1 Asia / #10 World.", tags: ["waterpark","largest","slides","family","day-trip"], mapsUrl: "https://maps.google.com/?q=Ramayana+Water+Park", verified: "2026-04-27" },
  { id: "af-academy-pattaya", name: "AF Academy Football School Pattaya", category: "kids-youth", area: "Naklua HQ + Jomtien + Pratumnak + Central", address: "215/18 Moo 6, Tambon Na Kluea, Pattaya City 20150", phone: "+66 96 078 8308", website: "https://www.afacademy.pro/en", social: { instagram: "af_academy_thai" }, hours: "After-school sessions", priceRange: "฿฿", description: "From age 3 — youngest accepted in Pattaya football. Multi-location. Russian/English/Thai. Indoor + outdoor fields.", tags: ["football","ages-3-up","multi-location","russian-language","kids"], mapsUrl: "https://maps.google.com/?q=AF+Academy+Pattaya", verified: "2026-04-27" },
  { id: "diana-driving-range", name: "Diana Driving Range Pattaya", category: "golf", area: "Soi Diana / Central Pattaya", address: "Soi Diana, Central Pattaya", phone: "", website: "", social: {}, hours: "Daily 06:00-22:00", priceRange: "฿", distinction: "30 floodlit bays + 200-yard range + on-site restaurant", description: "30-bay floodlit dedicated driving range. 200-yard depth. On-site restaurant. Soi Diana area central. Professional teaching pros.", tags: ["driving-range","floodlit","30-bays","central","restaurant"], mapsUrl: "https://maps.google.com/?q=Diana+Driving+Range+Pattaya", verified: "2026-04-27" },

  { id: "pratumnak-fitness-park", name: "Pratumnak Fitness Park (Free Outdoor Calisthenics)", category: "fitness", area: "Pratumnak Soi 5", address: "Pratumnak Soi 5, Pratumnak Hill, Pattaya", phone: "", website: "", social: {}, hours: "Public dawn-22:00", priceRange: "฿", description: "Pattaya FREE outdoor public fitness park. Free weights + machines + cardio + calisthenics. Pratumnak Hill / Buddha Hill setting. Up to 75lb dumbbells.", tags: ["free","outdoor","calisthenics","weights","public"], mapsUrl: "https://maps.google.com/?q=Pratumnak+Fitness+Park", verified: "2026-04-27" },
  { id: "pattaya-bowl", name: "Pattaya Bowl", category: "clubs", area: "North Pattaya / Soi Regent Marina", address: "463/78 M.9, Soi Regent Marina, Pattaya 2nd Rd", phone: "", website: "", social: {}, hours: "Daily 10:00-02:00", priceRange: "฿฿", description: "North Pattaya ten-pin bowling alley. Late-night hours to 02:00. Family + group friendly.", tags: ["bowling","late-night","family","group-events"], mapsUrl: "https://maps.google.com/?q=Pattaya+Bowl", verified: "2026-04-27" },

  { id: "pattaya-park-water-fun", name: "Pattaya Park Water & Fun Park (Tower Jump)", category: "adventure", area: "S. Pattaya / Jomtien border", address: "Pattaya Park Beach Resort, Soi 12 Thappraya Rd", phone: "", website: "", social: {}, hours: "Daily 10:00-19:00", priceRange: "฿฿", description: "Original Pattaya 1989 complex. Tower Jump (170m zip line from 56th floor) + water park + private beach + amusement park.", tags: ["tower-jump","water-park","beach","amusement","original","family"], mapsUrl: "https://maps.google.com/?q=Pattaya+Park+Tower", verified: "2026-04-27" },

  { id: "thai-sky-adventures-skydive", name: "Thai Sky Adventures (Skydive Pattaya)", category: "adventure", area: "Drop zone 25 km north Pattaya", address: "Drop zone 25 km north Pattaya — Pattaya pickup", phone: "", website: "https://thaiskyadventures.com/", social: {}, hours: "Daily — 07:00 or 10:00 AM pickup", priceRange: "฿฿฿฿", description: "Southeast Asia only full-time skydive drop zone. 25+ years. Tandem from 13,000 ft. 60s freefall at 200 km/h. Free Pattaya pickup.", tags: ["skydive","tandem","adrenaline","bucket-list","only-SE-Asia-full-time"], mapsUrl: "https://maps.google.com/?q=Thai+Sky+Adventures+Skydive", verified: "2026-04-27" },
  { id: "thai-polo-equestrian-club", name: "Thai Polo & Equestrian Club", category: "equestrian", area: "Banglamung / Mabprachan Lake (25 min N of Pattaya)", address: "Banglamung, near Mabhrachan Lake, Pattaya", phone: "", website: "https://www.thai-polo-club.com/", social: { facebook: "thaipolo.equestrianclub" }, hours: "Daily", priceRange: "฿฿฿฿", description: "Largest multi-functional polo + equestrian in all Asia. 250 hectares. 3 polo fields + 2 practice. 250+ stables. Endurance + Derby. Argentinian vet GM.", tags: ["polo","equestrian","largest-in-asia","international","derby","endurance"], mapsUrl: "https://maps.google.com/?q=Thai+Polo+Equestrian+Club+Pattaya", verified: "2026-04-27" },

  { id: "bira-circuit", name: "Bira Circuit (FIA Motor Racing Track)", category: "adventure", area: "Banglamung — 15 km NE Pattaya", address: "111 Moo 5, Banglamung, Chonburi", phone: "", website: "https://bira.co.th/", social: {}, hours: "Track days variable", priceRange: "฿฿฿", description: "Thailand first FIA-standard motor racing circuit. 2.41 km. 30 pit garages. 30,000 spectator capacity. SEATCZC + Asian Formula 2000 host since 1990s. Named after Prince Birabongse - Thailand first F1 driver.", tags: ["motor-racing","fia-standard","track-day","motorsport","first-thailand"], mapsUrl: "https://maps.google.com/?q=Bira+Circuit+Pattaya", verified: "2026-04-27" },
  { id: "jumpz-trampoline-park", name: "JumpZ Trampoline Park (Harbor Pattaya)", category: "kids-youth", area: "Harbor Pattaya Shopping Mall", address: "Harbor Pattaya Mall, 6F, Central Pattaya Rd", phone: "", website: "", social: {}, hours: "Daily 10:30-19:30", priceRange: "฿฿", description: "Pattaya main indoor trampoline park. 6th floor Harbor Pattaya Mall. Indoor AC family activity.", tags: ["trampoline","kids","family","indoor","mall"], mapsUrl: "https://maps.google.com/?q=JumpZ+Trampoline+Park+Pattaya", verified: "2026-04-27" },

  { id: "pattaya-shooting-park", name: "Pattaya Shooting Park", category: "adventure", area: "Soi Khao Mai Kaew / East Pattaya", address: "8 Moo 4, Soi Khao Mai Kaew, Pattaya", phone: "", website: "", social: {}, hours: "Daily 09:00-19:00", priceRange: "฿฿", description: "Largest outdoor shooting range in Pattaya. Diverse firearms (.22, .38, .45, 9mm, shotguns). Free hotel pickup in most packages.", tags: ["shooting","outdoor","firearms","adrenaline","largest-outdoor"], mapsUrl: "https://maps.google.com/?q=Pattaya+Shooting+Park", verified: "2026-04-27" },
  { id: "dragon-shooting-club", name: "Dragon Shooting Club Pattaya", category: "adventure", area: "Pattaya", address: "Pattaya, Bang Lamung, Chonburi", phone: "", website: "https://www.dragonshootingclub.com/", social: {}, hours: "Daily", priceRange: "฿฿", description: "Largest indoor shooting range in Thailand. 20 standard + 3 private VIP lanes. Modern firearms. Fully air-conditioned.", tags: ["shooting","indoor","largest-indoor","AC","vip-lanes"], mapsUrl: "https://maps.google.com/?q=Dragon+Shooting+Club+Pattaya", verified: "2026-04-27" },
  { id: "thai-wake-park", name: "Thai Wake Park Pattaya", category: "watersports", area: "Mabprachan Lake / East Pattaya", address: "Near Mabprachan Lake, East Pattaya", phone: "", website: "https://www.thaiwakepark.com/pattaya.html", social: {}, hours: "Daily", priceRange: "฿฿", description: "Pattaya only cable wakeboarding park. Two lakes (beginner + advanced). All equipment included.", tags: ["cable-wake","wakeboarding","two-lakes","mabprachan"], mapsUrl: "https://maps.google.com/?q=Thai+Wake+Park+Pattaya", verified: "2026-04-27" },
  { id: "pattaya-padel-club", name: "Pattaya Padel Club", category: "racquet", area: "Mabprachan Lake / East Pattaya", address: "Mabprachan Lake, East Pattaya", phone: "", website: "http://pattayapadelclub.com/", social: { instagram: "pattaya.padel.club" }, hours: "Daily", priceRange: "฿฿", description: "Lakeside padel courts on Mabprachan Reservoir. Pattaya second padel facility alongside Play Padel.", tags: ["padel","lakeside","mabprachan","doubles"], mapsUrl: "https://maps.google.com/?q=Pattaya+Padel+Club", verified: "2026-04-27" },

  { id: "sailbreeze-ocean-marina", name: "SailBreeze Sailing School @ Ocean Marina", category: "watersports", area: "Na Jomtien — Ocean Marina", address: "Ocean Marina Yacht Club, 274/1-3 Sukhumvit Rd, Na Jomtien, Sattahip 20250", phone: "", website: "https://www.sailbreeze.org/", social: {}, hours: "Daily — verify", priceRange: "฿฿฿", description: "Thailand most experienced sailing school (20+ years). Based at Ocean Marina Jomtien — Southeast Asia largest marina (450+ berths). IYT certification + yacht charters.", tags: ["sailing","yacht-charter","iyt","largest-marina","20-years"], mapsUrl: "https://maps.google.com/?q=SailBreeze+Ocean+Marina+Pattaya", verified: "2026-04-27" },
  { id: "pattaya-cycling-clubs", name: "Pattaya Cycling Clubs", category: "clubs", area: "Various — meet points across Pattaya", address: "Various weekly meeting points", phone: "", website: "", social: {}, hours: "Weekend mornings", priceRange: "฿", description: "Multiple road and MTB clubs. Cuore Masters Team + Monkey Xtreme + Jomtien Cycling + Pattaya MTB. Free to ฿2,000/year.", tags: ["cycling","road","mtb","weekend-rides","community"], mapsUrl: "https://maps.google.com/?q=Pattaya+Cycling+Clubs", verified: "2026-04-27" },
  { id: "pattaya-petanque-club", name: "Pattaya Sai 3 Petanque Club", category: "clubs", area: "Soi 3 — Central Pattaya", address: "Soi 3, Pattaya", phone: "", website: "", social: {}, hours: "Afternoon-evening", priceRange: "฿", description: "French-influenced petanque community. Central Pattaya Soi 3. All ages, drop-in friendly.", tags: ["petanque","boules","french","social","community"], mapsUrl: "https://maps.google.com/?q=Pattaya+Sai+3+Petanque", verified: "2026-04-27" },
  { id: "jomtien-beach-volleyball", name: "Jomtien Beach Volleyball", category: "clubs", area: "Jomtien Beach", address: "Jomtien Beach, Pattaya", phone: "", website: "", social: { instagram: "pattaya_beach_volley" }, hours: "Daily afternoon-evening", priceRange: "฿", description: "Pattaya beach volleyball community. Multiple Jomtien courts. Free pickup play. Mixed Thai-international.", tags: ["beach-volleyball","free","pickup-play","jomtien","community"], mapsUrl: "https://maps.google.com/?q=Jomtien+Beach+Volleyball", verified: "2026-04-27" },

  { id: "adventure-divers-pattaya", name: "Adventure Divers Pattaya", category: "watersports", area: "Central Pattaya / Bali Hai Pier", address: "Pattaya, Bang Lamung — Bali Hai Pier departures", phone: "", website: "https://pattayadivers.com/", social: {}, hours: "Daily — boat departures morning", priceRange: "฿฿", description: "Established 1998. 27+ years operating. Own dive boat MV Saifon. Full PADI pipeline. HTMS Khram wreck specialist. English/Russian/Thai instruction.", tags: ["padi","established-1998","own-boat","wreck-diving","trilingual"], mapsUrl: "https://maps.google.com/?q=Adventure+Divers+Pattaya", verified: "2026-04-27" },
  { id: "tarzan-adventure-pattaya", name: "Tarzan Adventure Pattaya (Zipline)", category: "adventure", area: "Na Chom Thian / Sattahip", address: "108/14 Moo 6, Na Chom Thian, Sattahip 20250", phone: "", website: "", social: { facebook: "TarzanZipline", instagram: "tarzanziplinepattaya" }, hours: "Daily 09:00-18:00", priceRange: "฿฿", description: "Pattaya jungle zipline park. 25-platform full course + half + kids. Bridges, ladders, abseil, ropes. Near Golden Cliff Temple.", tags: ["zipline","adventure-park","jungle","family","sattahip"], mapsUrl: "https://maps.google.com/?q=Tarzan+Adventure+Pattaya", verified: "2026-04-27" },
  { id: "pattaya-lawn-bowls", name: "Pattaya Lawn Bowls Clubs", category: "clubs", area: "Banchang + Jomtien + multiple", address: "Banchang covered facility + Paradise Jomtien + The Retreat", phone: "", website: "", social: {}, hours: "Mon/Wed/Fri 10:00 roll-up", priceRange: "฿", description: "Three lawn bowls facilities. 14+ artificial rinks total. Banchang ฿250/day all-inclusive. Pattaya Sports Club League runs year-round.", tags: ["lawn-bowls","british","commonwealth","three-facilities","covered-rinks"], mapsUrl: "https://maps.google.com/?q=Pattaya+Lawn+Bowls", verified: "2026-04-27" },
  { id: "max-muay-thai-stadium", name: "MAX Muay Thai Stadium Pattaya", category: "muay-thai", area: "Sukhumvit / King Power", address: "Sukhumvit Rd near Central Pattaya Rd, next to King Power Pattaya", phone: "", website: "https://www.muaythaistadium.com/max-pattaya", social: {}, hours: "Fights nightly 19:45-20:45 (doors 18:45)", priceRange: "฿฿฿", description: "Pattaya only daily Muay Thai stadium. 3 fights per card every night. MAX World Championships hosting. Modern tourist-friendly production. Sukhumvit / King Power location.", tags: ["stadium","daily-fights","spectator","max-championships","sukhumvit"], mapsUrl: "https://maps.google.com/?q=MAX+Muay+Thai+Stadium+Pattaya", verified: "2026-04-27" }










];

window.GYMS = GYMS;
window.CATEGORIES = CATEGORIES;
